/**
 * Amplify client configuration for the frontend.
 *
 * In a deployed Amplify Gen 2 project, the `amplify_outputs.json` file is
 * auto-generated by `ampx sandbox` or `ampx deploy`. This module provides
 * a typed configuration object that the app uses to initialize Amplify.
 *
 * Usage in main.tsx:
 *   import { Amplify } from 'aws-amplify';
 *   import outputs from '../amplify_outputs.json';
 *   Amplify.configure(outputs);
 *
 * For local development without a sandbox, this file exports a fallback
 * configuration structure that documents the expected shape.
 */

/**
 * Storage path helpers matching the S3 prefix structure defined in the design.
 */
export const StoragePaths = {
  /** Raw CSV upload path: uploads/{stage}/{yyyy}/{mm}/{dd}/{uploadId}/raw.csv */
  rawUpload: (stage: string, date: Date, uploadId: string) => {
    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, '0');
    const dd = String(date.getDate()).padStart(2, '0');
    return `uploads/${stage}/${yyyy}/${mm}/${dd}/${uploadId}/raw.csv`;
  },

  /** Normalized data path: normalized/{stage}/{uploadId}/normalized.json */
  normalized: (stage: string, uploadId: string) =>
    `normalized/${stage}/${uploadId}/normalized.json`,

  /** Correction XML path: corrections/{correctionId}/correction.xml */
  correction: (correctionId: string) =>
    `corrections/${correctionId}/correction.xml`,
} as const;

/**
 * User group constants matching Cognito group configuration.
 */
export const UserGroups = {
  ADMINISTRATOR: 'Administrator',
  OPERATOR: 'Operator',
} as const;

export type UserGroup = (typeof UserGroups)[keyof typeof UserGroups];

/**
 * Pipeline stages for the data reconciliation cascade.
 */
export const Stages = {
  GEOPOS_LOCAL: 'geopos-local',
  GEOPOS_CENTRAL: 'geopos-central',
  INTEGRACION: 'integracion',
  PS_CK: 'ps-ck',
} as const;

export type Stage = (typeof Stages)[keyof typeof Stages];

/**
 * Comparison pairs: each pair defines source → target for progressive comparison.
 */
export const ComparisonPairs = [
  { source: Stages.GEOPOS_LOCAL, target: Stages.GEOPOS_CENTRAL },
  { source: Stages.GEOPOS_CENTRAL, target: Stages.INTEGRACION },
  { source: Stages.INTEGRACION, target: Stages.PS_CK },
] as const;
