import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
import App from './App';

/**
 * Configure Amplify with the auto-generated outputs.
 * The amplify_outputs.json file is generated by `npx ampx sandbox` or `npx ampx deploy`.
 */
async function configureAmplify() {
  try {
    const outputs = await import('../amplify_outputs.json');
    Amplify.configure(outputs.default);
  } catch {
    console.warn(
      'amplify_outputs.json not found. Run `npx ampx sandbox` to generate it. ' +
      'The app will render but AWS services will not be available.'
    );
  }
}

configureAmplify().then(() => {
  createRoot(document.getElementById('root')!).render(
    <StrictMode>
      <Authenticator.Provider>
        <App />
      </Authenticator.Provider>
    </StrictMode>,
  );
});
